repos:
    - repo: local
      hooks:
        - id: YAPF
          name: YAPF 🧹
          entry: zsh -c 'yapf --in-place *.py'
          language: system
          always_run: true
          pass_filenames: true
        - id: isort
          name: isort 📚
          entry: zsh -c 'isort .'
          language: system
          always_run: true
          pass_filenames: true
